// frontend/src/App.vue
<template>
  <div class="flex h-screen bg-[var(--bg)] text-[var(--ink)] font-sans overflow-hidden app"
    :class="{'activity-collapsed': activityCollapsed}">
    <ActivityBar
      :active="activePage"
      :collapsed="activityCollapsed"
      @select="setActivePage"
      @toggle="activityCollapsed = !activityCollapsed"
      @toggle-sidebar="sidebarCollapsed = !sidebarCollapsed"
    />
    <Sidebar
      :active="activePage"
      :collapsed="sidebarCollapsed"
      @select="setActivePage"
      @toggle="sidebarCollapsed = !sidebarCollapsed"
    />
    <div class="flex-1 flex flex-col min-w-0">
      <Topbar
        :crumb="pageLabels[activePage]?.label ?? 'MECH'"
        :python-status="pythonStatus"
        :collapsed="activityCollapsed"
        @toggle-cmd-palette="showCmdPalette = !showCmdPalette"
        @toggle-activity="activityCollapsed = !activityCollapsed"
      />
      <div class="flex-1 overflow-auto p-4">
        <template v-if="modelLoaded">
          <component
            :is="currentPageComponent"
            :key="activePage"
            v-bind="currentPageProps"
          />
        </template>
        <div v-else class="flex flex-col items-center justify-center h-full gap-4">
          <div class="text-[var(--ink-muted)] text-sm">Choose a model to load</div>
          <div class="flex gap-2 flex-wrap justify-center">
            <button
              v-for="name in availableModels"
              :key="name"
              @click="loadModel(name)"
              class="px-4 py-2 rounded-lg border-none bg-transparent text-[var(--text)] text-sm font-medium hover:bg-[var(--bg-hover)] transition-colors"
            >
              Load {{ name }}
            </button>
          </div>
        </div>
      </div>
    </div>
    <StatusBar :model-name="modelName" />
  </div>
</template>

<script setup lang="ts">
import { ref, computed, onMounted, watch, shallowRef } from 'vue';
import { useAppStore } from './store/app';
import { api } from './services/api';
import Sidebar from './components/Sidebar.vue';
import Topbar from './components/Topbar.vue';
import ActivityBar from './components/ActivityBar.vue';
import StatusBar from './components/StatusBar.vue';

const store = useAppStore();

const activePage = computed({
  get: () => store.activePage,
  set: (v: string) => store.setActivePage(v),
});
const sidebarCollapsed = computed({
  get: () => store.sidebarCollapsed,
  set: (v: boolean) => store.set({ sidebarCollapsed: v }),
});
const activityCollapsed = computed({
  get: () => store.activityCollapsed,
  set: (v: boolean) => store.set({ activityCollapsed: v }),
});

const showCmdPalette = ref(false);
const modelLoaded = ref(false);
const modelName = ref('gpt2');
const availableModels = ref<string[]>([]);
const pythonStatus = ref<'connected' | 'offline' | 'connecting'>('connecting');

const PAGE_COMPONENTS: Record<string, () => Promise<{ default: any }>> = {};

const currentPageComponent = shallowRef<any>(null);
const currentPageProps = ref<Record<string, unknown>>({});

const pageLabels: Record<string, { label: string }> = {
  explorer: { label: 'Model Explorer' },
  gpt2: { label: 'GPT-2 Live' },
  gpt2explorer: { label: 'GPT-2 Neuron Explorer' },
  transformer: { label: 'Transformer Visualizer' },
  transformerExplorer: { label: 'Transformer Explorer' },
  workspace: { label: 'Workspace' },
  models: { label: 'Models' },
  prompts: { label: 'Prompts' },
  debugger: { label: 'Debugger' },
  experiments: { label: 'Experiments' },
  sessions: { label: 'Sessions' },
  reports: { label: 'Reports' },
  settings: { label: 'Settings' },
  logging: { label: 'Logging' },
  build: { label: 'Build' },
  neuralexplorer: { label: 'Neural Explorer' },
  benchmark: { label: 'Benchmark' },
  benchmarksuite: { label: 'Benchmark Suite' },
  knowledgegraph: { label: 'Knowledge Graph' },
  circuitexplorer: { label: 'Circuit Explorer' },
  reasoning: { label: 'Reasoning' },
  evidencefusion: { label: 'Evidence Fusion' },
  campaigns: { label: 'Campaigns' },
  analytics: { label: 'Analytics' },
  health: { label: 'Health' },
  plugins: { label: 'Plugins' },
  notebook: { label: 'Research Notebook' },
  labnotebook: { label: 'Lab Notebook' },
  reproduction: { label: 'Paper Reproduction' },
  projects: { label: 'Projects' },
  recent: { label: 'Recent Files' },
};

function setActivePage(page: string) {
  store.setActivePage(page);
  if (typeof window !== 'undefined' && window.location.hash.slice(1) !== page) {
    window.location.hash = page;
  }
}

async function loadModel(name: string) {
  try {
    pythonStatus.value = 'connecting';
    await api.loadModel(name);
    modelLoaded.value = true;
    modelName.value = name;
    pythonStatus.value = 'connected';
  } catch {
    pythonStatus.value = 'offline';
  }
}

async function loadPageComponent(page: string) {
  const map: Record<string, () => Promise<{ default: any }>> = {
    explorer: () => import('./components/ModelExplorerView.vue'),
    gpt2: () => import('./components/Gpt2View.vue'),
    neuralexplorer: () => import('./components/NeuralExplorerView.vue'),
    transformerExplorer: () => import('./components/visualizations/TransformerExplorer.vue'),
    settings: () => import('./components/Settings.vue'),
    experiments: () => import('./components/ExperimentsView.vue'),
    sessions: () => import('./components/SessionsView.vue'),
    reports: () => import('./components/ReportsView.vue'),
    models: () => import('./components/ModelsView.vue'),
    prompts: () => import('./components/PromptsView.vue'),
    debugger: () => import('./components/DebuggerView.vue'),
    benchmark: () => import('./components/BenchmarkDashboard.vue'),
    benchmarksuite: () => import('./components/BenchmarkSuiteView.vue'),
    knowledgegraph: () => import('./components/KnowledgeGraphView.vue'),
    circuitexplorer: () => import('./components/CircuitExplorerView.vue'),
    reasoning: () => import('./components/ReasoningTraceView.vue'),
    evidencefusion: () => import('./components/EvidenceFusionView.vue'),
    campaigns: () => import('./components/CampaignWorkspaceView.vue'),
    analytics: () => import('./components/ResearchAnalyticsView.vue'),
    health: () => import('./components/ScientificHealthView.vue'),
    plugins: () => import('./components/PluginSDKView.vue'),
    notebook: () => import('./components/ResearchNotebook.vue'),
    labnotebook: () => import('./components/ExperimentNotebook.vue'),
    reproduction: () => import('./components/PaperReproductionView.vue'),
    projects: () => import('./components/Projects.vue'),
    recent: () => import('./components/RecentFiles.vue'),
    logging: () => import('./components/Logging.vue'),
    build: () => import('./components/BuildLog.vue'),
    workspace: () => import('./components/CampaignWorkspaceView.vue'),
     transformer: () => import('./components/TransformerVisualizer.vue'),
     gpt2explorer: () => import('./components/Gpt2View.vue'),
   };
  const loader = map[page];
  if (loader) {
    try {
      const mod = await loader();
      currentPageComponent.value = mod.default;
    } catch {
      currentPageComponent.value = null;
    }
  } else {
    currentPageComponent.value = null;
  }
}

watch(activePage, (p) => loadPageComponent(p), { immediate: true });

onMounted(async () => {
  const hash = window.location.hash.slice(1);
  if (hash && pageLabels[hash]) {
    store.setActivePage(hash);
  }
  window.addEventListener('hashchange', () => {
    const next = window.location.hash.slice(1);
    if (next && pageLabels[next]) store.setActivePage(next);
  });

  try {
    const res = await api.listModels();
    availableModels.value = res.models ?? [];
    pythonStatus.value = 'connected';
  } catch {
    pythonStatus.value = 'offline';
  }
});
</script>

// New folder (4)/src/App.jsx
import React, { useEffect, useState, useCallback } from 'react';
import Sidebar from './components/Sidebar.jsx';
import Topbar from './components/Topbar.jsx';
import Workspace from './components/Workspace.jsx';
import ModelsView from './components/ModelsView.jsx';
import PromptsView from './components/PromptsView.jsx';
import DebuggerView from './components/DebuggerView.jsx';
import Gpt2View from './components/Gpt2View.jsx';
import ExperimentsView from './components/ExperimentsView.jsx';
import SessionsView from './components/SessionsView.jsx';
import ReportsView from './components/ReportsView.jsx';
import Settings from './components/Settings.jsx';
import Logging from './components/Logging.jsx';
import BuildLog from './components/BuildLog.jsx';
import CommandPalette from './components/CommandPalette.jsx';
import DockManager from './components/DockManager.jsx';
import WorkspaceSharingModal from './components/WorkspaceSharingModal.jsx';
import ExtensionMarketplaceModal from './components/ExtensionMarketplaceModal.jsx';
import PublicationExportModal from './components/PublicationExportModal.jsx';
import NeuralExplorerView from './components/NeuralExplorerView.jsx';
import BenchmarkDashboard from './components/BenchmarkDashboard.jsx';
import KnowledgeGraphView from './components/KnowledgeGraphView.jsx';
import CircuitExplorerView from './components/CircuitExplorerView.jsx';

import ReasoningTraceView from './components/ReasoningTraceView.jsx';
import EvidenceFusionView from './components/EvidenceFusionView.jsx';
import DiscoveryMemoryModal from './components/DiscoveryMemoryModal.jsx';
import CampaignWorkspaceView from './components/CampaignWorkspaceView.jsx';
import ResearchAnalyticsView from './components/ResearchAnalyticsView.jsx';
import ScientificHealthView from './components/ScientificHealthView.jsx';
import PluginSDKView from './components/PluginSDKView.jsx';
import BenchmarkSuiteView from './components/BenchmarkSuiteView.jsx';

const PAGES = {
  workspace:  { label: 'Workspace',    component: Workspace,    crumb: 'Workspace' },
  gpt2:       { label: 'GPT-2 Live',   component: Gpt2View,     crumb: 'GPT-2 Small — Live Interpretability' },
  campaigns: { label: 'Campaigns', component: CampaignWorkspaceView, crumb: 'Research Campaigns Workspace' },
  analytics: { label: 'Analytics', component: ResearchAnalyticsView, crumb: 'Multi-Campaign Meta-Learning Analytics' },
  models: { label: 'Models', component: ModelsView, crumb: 'Models Explorer' },
  prompts: { label: 'Prompts', component: PromptsView, crumb: 'Prompt Library' },
  debugger: { label: 'Debugger', component: DebuggerView, crumb: 'Circuit Debugger' },
  experiments: { label: 'Experiments', component: ExperimentsView, crumb: 'Experiments Matrix' },
  sessions: { label: 'Sessions', component: SessionsView, crumb: 'Session Explorer' },
  reports: { label: 'Reports', component: ReportsView, crumb: 'Research Reports' },
  settings: { label: 'Settings', component: Settings, crumb: 'Settings' },
  logging: { label: 'Logging', component: Logging, crumb: 'Logging' },
  build:          { label: 'Build',           component: BuildLog,          crumb: 'Build' },
  neuralexplorer: { label: 'Neural Explorer', component: NeuralExplorerView, crumb: 'Interactive Neural Explorer' },
  benchmark: { label: 'Benchmarks', component: BenchmarkDashboard, crumb: 'Reproducibility Benchmarks' },
  knowledgegraph: { label: 'Knowledge Graph', component: KnowledgeGraphView, crumb: 'Mechanistic Knowledge Graph' },
  circuitexplorer: { label: 'Circuit Explorer', component: CircuitExplorerView, crumb: 'Circuit Explorer' },
  reasoning: { label: 'Scientific Reasoning', component: ReasoningTraceView, crumb: 'Reasoning Trace Viewer' },
  evidencefusion: { label: 'Evidence Fusion', component: EvidenceFusionView, crumb: 'Evidence Fusion Engine' },
  health: { label: 'Scientific Health', component: ScientificHealthView, crumb: 'Continuous Validation & Regression Monitoring' },
  plugins: { label: 'Plugin SDK', component: PluginSDKView, crumb: 'Plugin SDK — Extend the Research Platform' },
  benchmarksuite: { label: 'MI Benchmarks', component: BenchmarkSuiteView, crumb: 'Real MI Benchmark Suite — 8 Tasks × 5 Models' },
};

export default function App() {
  const [active, setActive] = useState('workspace');
  const [settings, setSettings] = useState(null);
  const [pythonStatus, setPythonStatus] = useState('connecting');
  const [isCmdPaletteOpen, setIsCmdPaletteOpen] = useState(false);
  const [isDockOpen, setIsDockOpen] = useState(false);
  const [isShareOpen, setIsShareOpen] = useState(false);
  const [isMarketplaceOpen, setIsMarketplaceOpen] = useState(false);
  const [isPublicationOpen, setIsPublicationOpen] = useState(false);
  const [isDiscoveryMemoryOpen, setIsDiscoveryMemoryOpen] = useState(false);

  // Dynamic API getter resolving window.appApi
  const getApi = () => (typeof window !== 'undefined' ? window.appApi : undefined);

  // Load settings on mount and apply theme
  useEffect(() => {
    const api = getApi();
    if (!api || !api.getSettings) return;
    api.getSettings().then((s) => {
      setSettings(s);
      applyTheme(s?.theme || 'system');
    }).catch(() => undefined);
  }, []);

  // Ping Python sidecar
  useEffect(() => {
    let cancelled = false;
    const ping = async () => {
      const api = getApi();
      if (!api || !api.pythonPing) return;
      try {
        const res = await api.pythonPing();
        if (cancelled) return;
        const isConn = res && (res.ok || res.echo === 'pong');
        setPythonStatus(isConn ? 'connected' : 'error');
      } catch (err) {
        if (!cancelled) setPythonStatus('error');
      }
    };
    ping();
    const id = setInterval(ping, 3_000);
    return () => { cancelled = true; clearInterval(id); };
  }, []);

  // Global Ctrl+Shift+P shortcut
  useEffect(() => {
    const handleKeyDown = (e) => {
      if ((e.ctrlKey || e.metaKey) && e.shiftKey && (e.key === 'P' || e.key === 'p')) {
        e.preventDefault();
        setIsCmdPaletteOpen((prev) => !prev);
      }
    };
    window.addEventListener('keydown', handleKeyDown);
    return () => window.removeEventListener('keydown', handleKeyDown);
  }, []);

  const handleSettingsChange = useCallback(async (patch) => {
    const api = getApi();
    if (!api || !api.setSettings) return;
    const next = await api.setSettings(patch);
    setSettings(next);
    if (patch && patch.theme) applyTheme(patch.theme);
  }, []);

  const handleExecuteCommand = (cmdId) => {
    if (cmdId === 'load-model')          setActive('models');
    else if (cmdId === 'run-prompt')     setActive('gpt2');
    else if (cmdId === 'gpt2')           setActive('gpt2');
    else if (cmdId === 'open-experiments') setActive('experiments');
    else if (cmdId === 'open-sessions')  setActive('sessions');
    else if (cmdId === 'toggle-dock')    setIsDockOpen((prev) => !prev);
    else if (cmdId === 'toggle-theme') {
      const nextTheme = settings?.theme === 'light' ? 'dark' : 'light';
      handleSettingsChange({ theme: nextTheme });
    } else {
      setActive('debugger');
    }
  };

  const Page = PAGES[active]?.component || Workspace;
  const currentApi = getApi();

  return (
    <div className="app">
      <Sidebar
        pages={PAGES}
        active={active}
        onSelect={setActive}
      />
      <div className="main">
        <Topbar
          crumb={PAGES[active]?.crumb}
          pythonStatus={pythonStatus}
          onToggleDock={() => setIsDockOpen((prev) => !prev)}
          onToggleCmdPalette={() => setIsCmdPaletteOpen(true)}
          onOpenShare={() => setIsShareOpen(true)}
          onOpenMarketplace={() => setIsMarketplaceOpen(true)}
          onOpenPublication={() => setIsPublicationOpen(true)}
          onOpenDiscoveryMemory={() => setIsDiscoveryMemoryOpen(true)}
        />
        <div className="content" data-testid="content">
          {active === 'settings' ? (
            <Page
              settings={settings}
              onChange={handleSettingsChange}
              api={currentApi}
              onNavigate={setActive}
            />
          ) : (
            <Page api={currentApi} settings={settings} onNavigate={setActive} />
          )}
        </div>

        <DockManager
          isVisible={isDockOpen}
          onClose={() => setIsDockOpen(false)}
          activeTab={active}
          setActiveTab={setActive}
        />
      </div>

      <CommandPalette
        isOpen={isCmdPaletteOpen}
        onClose={() => setIsCmdPaletteOpen(false)}
        onExecuteCommand={handleExecuteCommand}
      />

      <WorkspaceSharingModal
        isOpen={isShareOpen}
        onClose={() => setIsShareOpen(false)}
      />

      <ExtensionMarketplaceModal
        isOpen={isMarketplaceOpen}
        onClose={() => setIsMarketplaceOpen(false)}
      />

      <PublicationExportModal
        isOpen={isPublicationOpen}
        onClose={() => setIsPublicationOpen(false)}
        figureData={{ title: "GPT-2 Mechanistic Analysis" }}
      />

      <DiscoveryMemoryModal
        isOpen={isDiscoveryMemoryOpen}
        onClose={() => setIsDiscoveryMemoryOpen(false)}
        onNavigate={setActive}
      />
    </div>
  );
}

function applyTheme(theme) {
  if (typeof document === 'undefined') return;
  const root = document.documentElement;
  if (theme === 'light') {
    root.setAttribute('data-theme', 'light');
  } else if (theme === 'dark') {
    root.setAttribute('data-theme', 'dark');
  } else {
    root.removeAttribute('data-theme');
  }
}
