// frontend/src/components/CircuitExplorerView.vue
<template>
  <div class="explorer-page p-4">
    <h2 class="text-lg font-bold text-[var(--ink)]">Circuit Explorer</h2>
    <p class="text-sm text-[var(--ink-muted-48)] mt-2">Hierarchical exploration of mechanistic circuits.</p>

    <div v-if="loading" class="text-sm text-[var(--ink-muted-48)] mt-4">
      Loading circuits from the backend…
    </div>
    <div v-else-if="error" class="text-sm mt-4" style="color: var(--danger, #ef4444)">
      Cannot reach the circuit registry: {{ error }}. Start the backend first.
    </div>
    <div v-else-if="circuits.length === 0" class="text-sm text-[var(--ink-muted-48)] mt-4">
      No circuits registered.
    </div>

    <div v-else class="mt-4 flex flex-col gap-3">
      <select v-model="selectedId" class="input-text" style="max-width: 420px">
        <option v-for="c in circuits" :key="c.circuit_id" :value="c.circuit_id">
          {{ c.name ?? c.circuit_id }}
        </option>
      </select>

      <div v-if="detail" class="flex flex-col gap-3">
        <div class="sae-subcard">
          <div class="text-xs font-bold">Evidence</div>
          <p class="text-sm mt-1">{{ detail.description ?? '—' }}</p>
        </div>

        <div class="sae-subcard">
          <div class="text-xs font-bold">Faithfulness</div>
          <div class="confidence-bar mt-1">
            <div class="confidence-track">
              <div
                class="confidence-fill"
                :style="{ width: faithfulnessPct + '%', background: 'var(--warning, #eab308)' }"
              />
            </div>
            <span class="confidence-value">{{ faithfulnessLabel }}</span>
          </div>
        </div>

        <div class="sae-subcard">
          <div class="text-xs font-bold mb-2">Attention Heads</div>
          <div class="flex flex-wrap gap-2">
            <span v-if="heads.length === 0" class="text-sm text-[var(--ink-muted-48)]">None listed</span>
            <span v-for="h in heads" :key="h.node_id" class="member-chip" :title="h.description ?? ''">
              {{ h.label }}{{ h.importance_score !== undefined ? ` (${h.importance_score})` : '' }}
            </span>
          </div>
        </div>

        <div class="sae-subcard">
          <div class="text-xs font-bold mb-2">Other Components</div>
          <div class="flex flex-wrap gap-2">
            <span v-if="others.length === 0" class="text-sm text-[var(--ink-muted-48)]">None listed</span>
            <span v-for="n in others" :key="n.node_id" class="member-chip" :title="n.description ?? ''">
              {{ n.label }}
            </span>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed, onMounted, ref, watch } from 'vue';

interface CircuitSummary {
  circuit_id: string;
  name?: string;
}

interface CircuitNode {
  node_id: string;
  node_type: string;
  label: string;
  description?: string;
  importance_score?: number;
}

interface CircuitDetail extends CircuitSummary {
  description?: string;
  faithfulness?: number;
  nodes?: CircuitNode[];
}

const circuits = ref<CircuitSummary[]>([]);
const selectedId = ref('');
const detail = ref<CircuitDetail | null>(null);
const loading = ref(true);
const error = ref<string | null>(null);

async function getJSON(path: string): Promise<any> {
  const res = await fetch(`/api${path}`);
  if (!res.ok) throw new Error(`GET ${path}: ${res.status}`);
  return res.json();
}

onMounted(async () => {
  try {
    const data = await getJSON('/circuits');
    const list = Array.isArray(data) ? data : data.circuits ?? [];
    circuits.value = list;
    if (list.length > 0) selectedId.value = list[0].circuit_id;
  } catch (e) {
    error.value = e instanceof Error ? e.message : String(e);
  } finally {
    loading.value = false;
  }
});

watch(selectedId, async id => {
  detail.value = null;
  if (!id) return;
  try {
    detail.value = await getJSON(`/circuits/${encodeURIComponent(id)}`);
  } catch {
    detail.value = null;
  }
});

const heads = computed(() => (detail.value?.nodes ?? []).filter(n => n.node_type === 'attention_head'));
const others = computed(() => (detail.value?.nodes ?? []).filter(n => n.node_type !== 'attention_head'));
const faithfulnessPct = computed(() => Math.round(((detail.value?.faithfulness ?? 0)) * 100));
const faithfulnessLabel = computed(() =>
  detail.value?.faithfulness === undefined || detail.value?.faithfulness === null
    ? '—'
    : `${Math.round((detail.value.faithfulness ?? 0) * 100)}%`,
);
</script>

// frontend/src/components/CircuitExplorerView.jsx
import React, { useEffect, useState } from 'react';
import { colors } from '../design/tokens/colors';

const API_BASE = 'http://localhost:8000/api';

async function getJSON(path) {
  const res = await fetch(`${API_BASE}${path}`);
  if (!res.ok) throw new Error(`GET ${path}: ${res.status}`);
  return res.json();
}

export default function CircuitExplorerView({ api }) {
  const [circuits, setCircuits] = useState([]);
  const [selectedId, setSelectedId] = useState('');
  const [detail, setDetail] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);

  useEffect(() => {
    let live = true;
    getJSON('/circuits')
      .then(data => {
        if (!live) return;
        const list = Array.isArray(data) ? data : data.circuits ?? [];
        setCircuits(list);
        if (list.length > 0) setSelectedId(list[0].circuit_id);
        setLoading(false);
      })
      .catch(e => {
        if (live) {
          setError(e instanceof Error ? e.message : String(e));
          setLoading(false);
        }
      });
    return () => {
      live = false;
    };
  }, []);

  useEffect(() => {
    if (!selectedId) {
      setDetail(null);
      return;
    }
    let live = true;
    setDetail(null);
    getJSON(`/circuits/${encodeURIComponent(selectedId)}`)
      .then(data => {
        if (live) setDetail(data);
      })
      .catch(() => {
        if (live) setDetail(null);
      });
    return () => {
      live = false;
    };
  }, [selectedId]);

  const nodes = detail?.nodes ?? [];
  const heads = nodes.filter(n => n.node_type === 'attention_head');
  const others = nodes.filter(n => n.node_type !== 'attention_head');
  const score = detail ? detail.faithfulness ?? null : null;

  return (
    <div className="explorer-page">
      <div className="explorer-header">
        <h1>Circuit Explorer</h1>
        <p className="hint">Hierarchical exploration of mechanistic circuits.</p>
      </div>

      {loading && <p className="hint">Loading circuits from the backend…</p>}
      {error && (
        <p className="hint" style={{ color: 'var(--danger, #ef4444)' }}>
          Cannot reach the circuit registry: {error}. Start the backend first.
        </p>
      )}

      {!loading && !error && circuits.length === 0 && (
        <p className="hint">No circuits registered.</p>
      )}

      {!loading && !error && circuits.length > 0 && (
        <div className="explorer-split">
          <div className="explorer-panel">
            <h2>Circuit Selection</h2>

            <select
              value={selectedId}
              onChange={e => setSelectedId(e.target.value)}
              className="input-text"
              style={{ marginBottom: 24 }}
            >
              {circuits.map(c => (
                <option key={c.circuit_id} value={c.circuit_id}>
                  {c.name ?? c.circuit_id}
                </option>
              ))}
            </select>

            {detail && (
              <>
                <div className="evidence-block" style={{ borderLeftColor: colors.primary }}>
                  <div className="evidence-label">Evidence</div>
                  <p className="evidence-text">{detail.description ?? '—'}</p>
                </div>

                <div className="evidence-block" style={{ borderLeftColor: colors.warning }}>
                  <div className="evidence-label">Faithfulness</div>
                  <div className="confidence-bar">
                    <div className="confidence-track">
                      <div
                        className="confidence-fill"
                        style={{
                          width: `${Math.round((score ?? 0) * 100)}%`,
                          background: colors.warning,
                        }}
                      />
                    </div>
                    <span className="confidence-value">
                      {score === null ? '—' : `${Math.round(score * 100)}%`}
                    </span>
                  </div>
                </div>
              </>
            )}
          </div>

          <div className="explorer-panel" style={{ flex: 2 }}>
            <h2>Members & Components</h2>

            {!detail && <p className="hint">Select a circuit to inspect its members.</p>}

            {detail && (
              <div className="component-list">
                <div className="component-card">
                  <div className="component-header">
                    <h3 style={{ color: colors.bodyMuted }}>Attention Heads</h3>
                  </div>
                  <div className="component-tags">
                    {heads.length === 0 && <span className="hint">None listed</span>}
                    {heads.map(h => (
                      <span className="chip" key={h.node_id} title={h.description ?? ''}>
                        {h.label}
                        {h.importance_score !== undefined ? ` (${h.importance_score})` : ''}
                      </span>
                    ))}
                  </div>
                </div>

                <div className="component-card">
                  <h3 style={{ color: colors.ink, margin: '0 0 12px 0' }}>Other Components</h3>
                  <div className="component-tags">
                    {others.length === 0 && <span className="hint">None listed</span>}
                    {others.map(n => (
                      <span className="chip" key={n.node_id} title={n.description ?? ''}>
                        {n.label}
                      </span>
                    ))}
                  </div>
                </div>
              </div>
            )}
          </div>
        </div>
      )}
    </div>
  );
}
