// frontend/src/components/Topbar.jsx
import React from 'react';
import { Brain, PanelLeft, Sidebar, Share2, Store, FileUp, Command, CircleDot } from 'lucide-react';
import { colors, radii, spacing, typography } from '../design/tokens';
import { Button } from '../design/components/Button';

export default function Topbar({
  crumb,
  pythonStatus,
  onToggleDock,
  onToggleCmdPalette,
  onOpenShare,
  onOpenMarketplace,
  onOpenPublication,
  onOpenDiscoveryMemory,
  sidebarCollapsed,
  onToggleSidebar,
  activityCollapsed,
  onToggleActivity,
}) {
  const statusLabel = pythonStatus === 'connected'
    ? 'Connected'
    : pythonStatus === 'connecting'
      ? '…'
      : 'Offline';

  return (
    <header
      className="topbar"
      style={{
        backgroundColor: colors.canvas,
        borderBottom: `1px solid ${colors.hairline}`,
        height: '46px',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'space-between',
        padding: `0 ${spacing.lg}`,
        gridArea: 'topbar',
      }}
    >
      <div style={{ display: 'flex', alignItems: 'center', gap: spacing.sm }}>
        <button
          onClick={onToggleActivity}
          title={activityCollapsed ? 'Expand activity bar' : 'Collapse activity bar'}
          style={{
            width: '32px',
            height: '32px',
            borderRadius: radii.sm,
            border: 'none',
            background: 'transparent',
            color: colors.inkMuted80,
            cursor: 'pointer',
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
          }}
        >
          <PanelLeft size={16} strokeWidth={1.75} />
        </button>
        <button
          onClick={onToggleSidebar}
          title={sidebarCollapsed ? 'Expand sidebar' : 'Collapse sidebar'}
          style={{
            width: '32px',
            height: '32px',
            borderRadius: radii.sm,
            border: 'none',
            background: 'transparent',
            color: colors.inkMuted80,
            cursor: 'pointer',
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
          }}
        >
          <Sidebar size={16} strokeWidth={1.75} />
        </button>
        <span
          style={{
            fontFamily: typography.tagline.fontFamily,
            fontSize: typography.tagline.fontSize,
            fontWeight: typography.tagline.fontWeight,
            letterSpacing: typography.tagline.letterSpacing,
            color: colors.ink,
          }}
        >
          {crumb}
        </span>
      </div>

      <div style={{ display: 'flex', alignItems: 'center', gap: spacing.xs }}>
        <Button variant="dark-utility" onClick={onOpenDiscoveryMemory} style={{ padding: `${spacing.xs} ${spacing.sm}` }}>
          <Brain size={14} /> Mem
        </Button>
        <Button variant="dark-utility" onClick={onToggleDock} style={{ padding: `${spacing.xs} ${spacing.sm}` }}>
          <PanelLeft size={14} /> Dock
        </Button>
        <Button variant="dark-utility" onClick={onOpenShare} style={{ padding: `${spacing.xs} ${spacing.sm}` }}>
          <Share2 size={14} /> Share
        </Button>
        <Button variant="dark-utility" onClick={onOpenMarketplace} style={{ padding: `${spacing.xs} ${spacing.sm}` }}>
          <Store size={14} /> Market
        </Button>
        <Button variant="dark-utility" onClick={onOpenPublication} style={{ padding: `${spacing.xs} ${spacing.sm}` }}>
          <FileUp size={14} /> Export
        </Button>
        <Button variant="dark-utility" onClick={onToggleCmdPalette} style={{ padding: `${spacing.xs} ${spacing.sm}` }}>
          <Command size={13} /> P
        </Button>
        <div
          data-testid="python-status"
          data-status={pythonStatus}
          style={{
            display: 'flex',
            alignItems: 'center',
            gap: spacing.xs,
            paddingLeft: spacing.sm,
            marginLeft: spacing.xs,
            borderLeft: `1px solid ${colors.border}`,
          }}
        >
          <span
            className={`dot ${pythonStatus === 'connected' ? 'connected' : pythonStatus === 'connecting' ? 'connecting' : ''}`}
            style={{
              width: '8px',
              height: '8px',
              borderRadius: '50%',
              backgroundColor: pythonStatus === 'connected' ? colors.success : pythonStatus === 'connecting' ? colors.warning : colors.inkMuted48,
            }}
          />
          <span style={{ fontFamily: typography.navLink.fontFamily, fontSize: typography.navLink.fontSize, color: colors.inkMuted80 }}>
            {statusLabel}
          </span>
        </div>
      </div>
    </header>
  );
}

// frontend/src/components/Topbar.vue
<template>
  <header
    class="flex items-center justify-between h-[46px] px-6 border-b border-[var(--hairline)] bg-[var(--canvas)]"
  >
    <div class="flex items-center gap-2">
      <span class="text-sm font-medium tracking-tight text-[var(--ink)]">
        {{ crumb }}
      </span>
    </div>

    <div class="flex items-center gap-1">
      <button
        :title="collapsed ? 'Expand activity bar' : 'Collapse activity bar'"
        @click="$emit('toggle-activity')"
        class="w-9 h-9 rounded-full border-none bg-transparent text-[var(--ink-muted-48)] cursor-pointer flex items-center justify-center hover:text-[var(--ink-muted-80)]"
      >
        <Settings :size="18" :stroke-width="1.75" />
      </button>

      <button
        class="flex items-center gap-1 px-2 py-1 rounded text-xs font-medium text-[var(--ink-muted-80)] hover:bg-[var(--accent-soft)] transition-colors"
        @click="$emit('toggle-cmd-palette')"
      >
        <Command :size="13" /> P
      </button>

      <div
        data-testid="python-status"
        class="flex items-center gap-1 pl-2 ml-1 border-l border-[var(--border)]"
      >
        <span
          class="w-2 h-2 rounded-full"
          :class="pythonStatus === 'connected' ? 'bg-[var(--text)]' : pythonStatus === 'connecting' ? 'bg-[var(--ink-muted-48)]' : 'bg-[var(--hairline)]'"
        />
        <span class="text-xs text-[var(--ink-muted-80)]">
          {{ statusLabel }}
        </span>
      </div>
    </div>
  </header>
</template>

<script setup lang="ts">
import { computed } from 'vue';
import { Command } from 'lucide-vue-next';

const props = defineProps<{
  crumb: string;
  pythonStatus: 'connected' | 'offline' | 'connecting';
  collapsed: boolean;
}>();

defineEmits<{
  'toggle-cmd-palette': [];
  'toggle-activity': [];
}>();

const statusLabel = computed(() =>
  props.pythonStatus === 'connected' ? 'Connected'
    : props.pythonStatus === 'connecting' ? '…'
      : 'Offline'
);
</script>
