// frontend/src/components/visualizations/TransformerExplorer.tsx
import React, { useState, useMemo } from 'react';
import { colors } from '../../design/tokens/colors';
import { AttentionHeatmap } from './panels/AttentionHeatmap';
import { ActivationHeatmap } from './panels/ActivationHeatmap';
import { NeuronUMAP } from './neuron-umap/NeuronUMAP';
import { buildNeuronPoints, idForHeadNeuron, parseNeuronId } from './neuron-umap/data';

function hexToRgb(hex: string): [number, number, number] {
  const n = parseInt(hex.slice(1), 16);
  return [(n >> 16) & 255, (n >> 8) & 255, n & 255];
}

function rgba(hex: string, a: number): string {
  const [r, g, b] = hexToRgb(hex);
  return `rgba(${r},${g},${b},${a})`;
}

interface Props {
  tokens: string[];
  layers: any[];
  numLayers: number;
  numHeads: number;
}

export function TransformerExplorer({ tokens, layers, numLayers, numHeads }: Props) {
  const [selectedLayer, setSelectedLayer] = useState(0);
  const [selectedHead, setSelectedHead] = useState(0);
  const [selectedNeuron, setSelectedNeuron] = useState<number | null>(null);
  const [hoveredToken, setHoveredToken] = useState<number | null>(null);
  const [activeTab, setActiveTab] = useState<'attention' | 'neurons' | 'spectrum' | 'compare' | 'umap'>('attention');
  const [compareHeads, setCompareHeads] = useState<number[]>([0, 1]);

  const layer = layers[selectedLayer];
  const head = layer?.heads[selectedHead];
  const neurons = head?.neurons ?? [];
  const matrix = head?.attentionMatrix ?? [];

  const headLabels = useMemo(() => Array.from({ length: numHeads }, (_, i) => `H${i}`), [numHeads]);

  const selNeuronData = selectedNeuron !== null ? neurons[selectedNeuron] : null;

  const umapPoints = useMemo(() => buildNeuronPoints(layers, tokens), [layers, tokens]);

  // Multi-head summary: compute average attention per head for the selected layer
  const layerHeadSummaries = useMemo(() => {
    if (!layer) return [];
    return layer.heads.map((h: any, i: number) => {
      const flat = (h.attentionMatrix as number[] | undefined)?.flat() ?? [];
      return {
        headIndex: i,
        avgActivation: flat.reduce((a: number, b: number) => a + b, 0) / (flat.length || 1),
        maxActivation: Math.max(...(flat.length ? flat : [0])),
      };
    });
  }, [layer]);

  // Token-level neuron activation: for each token, which neurons are most active
  const tokenNeuronMap = useMemo(() => {
    if (!selNeuronData?.tokenActivations || tokens.length === 0) return [];
    return tokens.map((t, i) => ({
      token: t,
      activation: selNeuronData.tokenActivations[i] ?? 0,
      idx: i,
    })).sort((a, b) => Math.abs(b.activation) - Math.abs(a.activation));
  }, [selNeuronData, tokens]);

  const bg = colors.canvasParchment;
  const cardBg = colors.canvas;
  const border = colors.border;
  const textColor = colors.ink;
  const mutedColor = colors.inkMuted48;

  const accent = colors.primary;

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: 12, fontFamily: 'system-ui, sans-serif', fontSize: 12, color: textColor }}>
      {/* ── Controls Bar (horizontal, full width) ────────────── */}
      <div style={{ display: 'flex', gap: 12, alignItems: 'center', flexWrap: 'wrap', background: cardBg, padding: 10, borderRadius: 8, border: `1px solid ${border}` }}>
        <label style={{ display: 'flex', alignItems: 'center', gap: 4 }}>
          <span style={{ color: mutedColor, fontWeight: 600 }}>Layer</span>
          <input type="range" min={0} max={numLayers - 1} value={selectedLayer}
            onChange={e => { setSelectedLayer(Number(e.target.value)); setSelectedHead(0); setSelectedNeuron(null); }}
            style={{ width: 120 }} />
          <span style={{ fontFamily: 'monospace', minWidth: 24, fontWeight: 700 }}>{selectedLayer}</span>
        </label>

        <label style={{ display: 'flex', alignItems: 'center', gap: 4 }}>
          <span style={{ color: mutedColor, fontWeight: 600 }}>Head</span>
          <select value={selectedHead} onChange={e => { setSelectedHead(Number(e.target.value)); setSelectedNeuron(null); }}
            style={{ background: bg, color: textColor, border: `1px solid ${border}`, borderRadius: 4, padding: '2px 4px', fontSize: 11 }}>
            {headLabels.map((l, i) => <option key={i} value={i}>{l}</option>)}
          </select>
        </label>

        <label style={{ display: 'flex', alignItems: 'center', gap: 4 }}>
          <span style={{ color: mutedColor, fontWeight: 600 }}>Neuron</span>
          <input type="range" min={0} max={Math.max(neurons.length - 1, 0)} value={selectedNeuron ?? 0}
            onChange={e => setSelectedNeuron(Number(e.target.value))}
            style={{ width: 120 }} disabled={neurons.length === 0} />
          <span style={{ fontFamily: 'monospace', minWidth: 24, fontWeight: 700 }}>{selectedNeuron ?? '—'}</span>
        </label>

        <div style={{ display: 'flex', gap: 2, marginLeft: 'auto' }}>
          {(['attention', 'neurons', 'spectrum', 'compare', 'umap'] as const).map(tab => (
            <button key={tab} onClick={() => setActiveTab(tab)}
              style={{
                background: activeTab === tab ? accent : bg,
                color: activeTab === tab ? colors.onDark : textColor,
                border: `1px solid ${border}`, borderRadius: 4,
                padding: '3px 10px', cursor: 'pointer', fontSize: 11, fontWeight: 600,
              }}>
              {tab.charAt(0).toUpperCase() + tab.slice(1)}
            </button>
          ))}
        </div>
      </div>

      {/* ── Multi-Head Overview (always visible in attention tab) ─── */}
      {activeTab === 'attention' && layer && (
        <div style={{ background: cardBg, borderRadius: 8, padding: 10, border: `1px solid ${border}` }}>
          <div style={{ fontWeight: 600, color: mutedColor, textTransform: 'uppercase', letterSpacing: 1, marginBottom: 6, fontSize: 11 }}>
            Layer {selectedLayer} — All Heads Overview
          </div>
          <div style={{ display: 'flex', gap: 4, flexWrap: 'wrap' }}>
            {layerHeadSummaries.map((s: any, i: number) => (
              <button key={i} onClick={() => { setSelectedHead(i); setSelectedNeuron(null); }}
                style={{
                  background: i === selectedHead ? accent : bg,
                  color: i === selectedHead ? colors.onDark : textColor,
                  border: `1px solid ${i === selectedHead ? accent : border}`,
                  borderRadius: 4, padding: '4px 8px', cursor: 'pointer',
                  fontSize: 10, fontWeight: i === selectedHead ? 700 : 400,
                  minWidth: 36, textAlign: 'center',
                }}>
                H{i}
                <div style={{ fontSize: 9, opacity: 0.7 }}>{s.avgActivation.toFixed(2)}</div>
              </button>
            ))}
          </div>
        </div>
      )}

      {/* ── Main Content (horizontal flow) ───────────────────── */}
      <div style={{ display: 'flex', flexDirection: 'row', gap: 12, overflowX: 'auto', alignItems: 'flex-start' }}>
        {/* Attention Heatmap */}
        {(activeTab === 'attention' || activeTab === 'compare') && (
          <div style={{ background: cardBg, borderRadius: 8, padding: 12, border: `1px solid ${border}`, flex: '1 1 0', minWidth: 340 }}>
            <div style={{ fontWeight: 600, color: mutedColor, textTransform: 'uppercase', letterSpacing: 1, marginBottom: 8, fontSize: 11 }}>
              Attention Heatmap — L{selectedLayer} H{selectedHead}
            </div>
            {matrix.length > 0 && tokens.length > 0 ? (
              <AttentionHeatmap
                matrix={matrix}
                tokens={tokens}
                hoveredToken={hoveredToken}
                onHoverToken={setHoveredToken}
              />
            ) : (
              <div className="hint">Run a prompt first to populate attention data.</div>
            )}
            {hoveredToken !== null && tokens[hoveredToken] && (
              <div style={{ marginTop: 6, fontSize: 11, color: mutedColor }}>
                Hovering: <strong>"{tokens[hoveredToken]}"</strong> (token {hoveredToken})
              </div>
            )}
          </div>
        )}

        {/* Neuron Activation Panel */}
        {(activeTab === 'neurons' || activeTab === 'spectrum') && (
          <div style={{ background: cardBg, borderRadius: 8, padding: 12, border: `1px solid ${border}`, flex: '1 1 0', minWidth: 340 }}>
            <div style={{ fontWeight: 600, color: mutedColor, textTransform: 'uppercase', letterSpacing: 1, marginBottom: 8, fontSize: 11 }}>
              Neuron Activations — Layer {selectedLayer}
            </div>
            {neurons.length > 0 ? (
              <ActivationHeatmap
                activations={neurons.map((n: any) => n.activation)}
                neuronIndex={selectedNeuron}
                onSelectNeuron={(i: number) => setSelectedNeuron(i)}
                tokens={tokens}
                neuronTokenActivations={neurons.map((n: any) => n.tokenActivations ?? null)}
              />
            ) : (
              <div className="hint">No neuron data for this layer.</div>
            )}
          </div>
        )}

        {/* Compare Panel */}
        {activeTab === 'compare' && (
          <>
            <div style={{ background: cardBg, borderRadius: 8, padding: 12, border: `1px solid ${border}`, flex: '1 1 0', minWidth: 340 }}>
              <div style={{ fontWeight: 600, color: mutedColor, textTransform: 'uppercase', letterSpacing: 1, marginBottom: 8, fontSize: 11 }}>
                Compare Heads — Layer {selectedLayer}
              </div>
              <div style={{ display: 'flex', gap: 8, marginBottom: 8 }}>
                <select value={compareHeads[0]} onChange={e => setCompareHeads([Number(e.target.value), compareHeads[1]])}
                  style={{ background: bg, color: textColor, border: `1px solid ${border}`, borderRadius: 4, padding: '2px 4px', fontSize: 11 }}>
                  {headLabels.map((l, i) => <option key={i} value={i}>{l}</option>)}
                </select>
                <span style={{ color: mutedColor, alignSelf: 'center' }}>vs</span>
                <select value={compareHeads[1]} onChange={e => setCompareHeads([compareHeads[0], Number(e.target.value)])}
                  style={{ background: bg, color: textColor, border: `1px solid ${border}`, borderRadius: 4, padding: '2px 4px', fontSize: 11 }}>
                  {headLabels.map((l, i) => <option key={i} value={i}>{l}</option>)}
                </select>
              </div>
              {layer?.heads[compareHeads[0]]?.attentionMatrix && layer?.heads[compareHeads[1]]?.attentionMatrix ? (
                <div style={{ display: 'flex', gap: 8 }}>
                  <div style={{ flex: 1 }}>
                    <div style={{ fontSize: 10, color: mutedColor, marginBottom: 4 }}>Head {compareHeads[0]}</div>
                    <AttentionHeatmap
                      matrix={layer.heads[compareHeads[0]].attentionMatrix}
                      tokens={tokens}
                      hoveredToken={null}
                      onHoverToken={() => {}}
                    />
                  </div>
                  <div style={{ flex: 1 }}>
                    <div style={{ fontSize: 10, color: mutedColor, marginBottom: 4 }}>Head {compareHeads[1]}</div>
                    <AttentionHeatmap
                      matrix={layer.heads[compareHeads[1]].attentionMatrix}
                      tokens={tokens}
                      hoveredToken={null}
                      onHoverToken={() => {}}
                    />
                  </div>
                </div>
              ) : (
                <div className="hint">Run a prompt first.</div>
              )}
            </div>

            <div style={{ background: cardBg, borderRadius: 8, padding: 12, border: `1px solid ${border}`, flex: '1 1 0', minWidth: 340 }}>
              <div style={{ fontWeight: 600, color: mutedColor, textTransform: 'uppercase', letterSpacing: 1, marginBottom: 8, fontSize: 11 }}>
                Head Similarity — Layer {selectedLayer}
              </div>
              <div style={{ display: 'flex', flexWrap: 'wrap', gap: 4 }}>
                {layerHeadSummaries.map((s: any, i: number) => {
                  const maxAvg = Math.max(...layerHeadSummaries.map((x: any) => x.avgActivation), 0.01);
                  const pct = (s.avgActivation / maxAvg) * 100;
                  return (
                    <div key={i} style={{
                      width: 36, height: 36, borderRadius: 4,
                      background: rgba(colors.primary, 0.1 + (pct / 100) * 0.9),
                      border: `1px solid ${border}`,
                      display: 'flex', alignItems: 'center', justifyContent: 'center',
                      fontSize: 9, fontWeight: 600, cursor: 'pointer',
                      color: pct > 50 ? colors.onDark : textColor,
                    }}
                      onClick={() => { setSelectedHead(i); setActiveTab('attention'); }}
                      title={`H${i}: avg=${s.avgActivation.toFixed(3)}, max=${s.maxActivation.toFixed(3)}`}>
                      H{i}
                    </div>
                  );
                })}
              </div>
            </div>
          </>
        )}
      </div>

      {/* ── Neuron UMAP (horizontal full-width) ───────────────── */}
      {activeTab === 'umap' && (
        <div style={{ background: cardBg, borderRadius: 8, padding: 12, border: `1px solid ${border}`, width: '100%' }}>
          <div style={{ fontWeight: 600, color: mutedColor, textTransform: 'uppercase', letterSpacing: 1, marginBottom: 8, fontSize: 11 }}>
            Neuron Map — All Layers &amp; Heads
          </div>
          <NeuronUMAP
            points={umapPoints}
            tokens={tokens}
            selectedId={selectedNeuron !== null ? idForHeadNeuron(selectedLayer, selectedHead, selectedNeuron) : null}
            onSelectNeuron={id => {
              const parsed = parseNeuronId(id);
              if (!parsed) {
                setSelectedNeuron(null);
                return;
              }
              if (parsed.head !== undefined) {
                setSelectedLayer(parsed.layer);
                setSelectedHead(parsed.head);
              }
              setSelectedNeuron(parsed.neuron);
            }}
            height={460}
          />
        </div>
      )}

      {/* ── Token Detail: which neurons fire for this token ──── */}
      {hoveredToken !== null && tokens[hoveredToken] && neurons.length > 0 && (
        <div style={{ background: cardBg, borderRadius: 8, padding: 12, border: `1px solid ${border}` }}>
          <div style={{ fontWeight: 600, color: mutedColor, textTransform: 'uppercase', letterSpacing: 1, marginBottom: 8, fontSize: 11 }}>
            Neurons Active for "{tokens[hoveredToken]}" (token {hoveredToken})
          </div>
          {neurons.length > 0 && (
            <ActivationHeatmap
              activations={neurons.map((n: any) => n.activation)}
              neuronIndex={selectedNeuron}
              onSelectNeuron={(i: number) => setSelectedNeuron(i)}
              tokens={tokens}
              neuronTokenActivations={neurons.map((n: any) => n.tokenActivations ?? null)}
            />
          )}
        </div>
      )}

      {/* ── Summary Bar ──────────────────────────────────────── */}
      <div style={{ display: 'flex', gap: 8, flexWrap: 'wrap', fontSize: 11, color: mutedColor }}>
        <span>Layers: {numLayers}</span>
        <span>Heads/Layer: {numHeads}</span>
        <span>Neurons/Layer: {neurons.length}</span>
        <span>Tokens: {tokens.length}</span>
        {selNeuronData && (
          <span>Neuron #{selNeuronData.index} activation: {selNeuronData.activation.toFixed(4)}</span>
        )}
        {hoveredToken !== null && tokens[hoveredToken] && (
          <span>Token: "{tokens[hoveredToken]}"</span>
        )}
      </div>
    </div>
  );
}

// frontend/src/components/visualizations/TransformerExplorer.vue
<template>
  <div class="flex flex-col gap-3 font-['system-ui',sans-serif] text-xs text-[var(--ink)]">
    <!-- ── Controls Bar ────────────── -->
    <div class="flex gap-3 items-center flex-wrap bg-[var(--canvas)] p-2.5 rounded-lg border border-[var(--border)]">
      <label class="flex items-center gap-1">
        <span class="text-[var(--ink-muted-48)] font-semibold">Layer</span>
        <input type="range" :min="0" :max="numLayers - 1" v-model.number="selectedLayer"
          @change="selectedHead = 0; selectedNeuron = null"
          class="w-[120px]" />
        <span class="font-mono min-w-[24px] font-bold">{{ selectedLayer }}</span>
      </label>

      <label class="flex items-center gap-1">
        <span class="text-[var(--ink-muted-48)] font-semibold">Head</span>
        <select v-model.number="selectedHead" @change="selectedNeuron = null"
          class="bg-[var(--canvas-parchment)] text-[var(--ink)] border border-[var(--border)] rounded px-1 py-0.5 text-[11px]">
          <option v-for="(l, i) in headLabels" :key="i" :value="i">{{ l }}</option>
        </select>
      </label>

      <label class="flex items-center gap-1">
        <span class="text-[var(--ink-muted-48)] font-semibold">Neuron</span>
        <input type="range" :min="0" :max="Math.max(neurons.length - 1, 0)" v-model.number="selectedNeuron"
          class="w-[120px]" :disabled="neurons.length === 0" />
        <span class="font-mono min-w-[24px] font-bold">{{ selectedNeuron ?? '—' }}</span>
      </label>

      <div class="flex gap-0.5 ml-auto">
        <button v-for="tab in tabs" :key="tab" @click="activeTab = tab"
          class="px-2.5 py-[3px] rounded text-[11px] font-semibold cursor-pointer border border-[var(--border)]"
          :class="activeTab === tab
            ? 'bg-[var(--primary)] text-[var(--on-dark)]'
            : 'bg-[var(--canvas-parchment)] text-[var(--ink)]'">
          {{ tab.charAt(0).toUpperCase() + tab.slice(1) }}
        </button>
      </div>
    </div>

    <!-- ── Multi-Head Overview ──────────── -->
    <div v-if="activeTab === 'attention' && layer" class="bg-[var(--canvas)] rounded-lg p-2.5 border border-[var(--border)]">
      <div class="font-semibold text-[var(--ink-muted-48)] uppercase tracking-widest mb-1.5 text-[11px]">
        Layer {{ selectedLayer }} — All Heads Overview
      </div>
      <div class="flex gap-1 flex-wrap">
        <button v-for="(s, i) in layerHeadSummaries" :key="i"
          @click="selectedHead = i; selectedNeuron = null"
          class="rounded px-2 py-1 cursor-pointer text-[10px] min-w-[36px] text-center border"
          :class="i === selectedHead
            ? 'bg-[var(--primary)] text-[var(--on-dark)] border-[var(--primary)] font-bold'
            : 'bg-[var(--canvas-parchment)] text-[var(--ink)] border-[var(--border)] font-normal'"
          :title="`H${i}: avg=${s.avgActivation.toFixed(3)}, max=${s.maxActivation.toFixed(3)}`">
          H{{ i }}
          <div class="text-[9px] opacity-70">{{ s.avgActivation.toFixed(2) }}</div>
        </button>
      </div>
    </div>

    <!-- ── Main Content (horizontal) ────── -->
    <div class="flex flex-row gap-3 overflow-x-auto items-start">
      <!-- Attention Heatmap -->
      <div v-if="activeTab === 'attention' || activeTab === 'compare'"
        class="bg-[var(--canvas)] rounded-lg p-3 border border-[var(--border)] flex-1 min-w-[340px]">
        <div class="font-semibold text-[var(--ink-muted-48)] uppercase tracking-widest mb-2 text-[11px]">
          Attention Heatmap — L{{ selectedLayer }} H{{ selectedHead }}
        </div>
        <template v-if="matrix.length > 0 && tokens.length > 0">
          <AttentionHeatmap :matrix="matrix" :tokens="tokens"
            :hoveredToken="hoveredToken" @hoverToken="hoveredToken = $event" />
        </template>
        <div v-else class="text-[var(--ink-muted-48)] text-xs">Run a prompt first to populate attention data.</div>
        <div v-if="hoveredToken !== null && tokens[hoveredToken]" class="mt-1.5 text-[11px] text-[var(--ink-muted-48)]">
          Hovering: <strong>"{{ tokens[hoveredToken] }}"</strong> (token {{ hoveredToken }})
        </div>
      </div>

      <!-- Neuron Activation Panel -->
      <div v-if="activeTab === 'neurons' || activeTab === 'spectrum'"
        class="bg-[var(--canvas)] rounded-lg p-3 border border-[var(--border)] flex-1 min-w-[340px]">
        <div class="font-semibold text-[var(--ink-muted-48)] uppercase tracking-widest mb-2 text-[11px]">
          Neuron Activations — Layer {{ selectedLayer }}
        </div>
        <template v-if="neurons.length > 0">
          <ActivationHeatmap :activations="neurons.map(n => n.activation)"
            :neuronIndex="selectedNeuron"
            @selectNeuron="(i) => selectedNeuron = i"
            :tokens="tokens"
            :neuronTokenActivations="neurons.map(n => n.tokenActivations ?? null)" />
        </template>
        <div v-else class="text-[var(--ink-muted-48)] text-xs">No neuron data for this layer.</div>
      </div>

      <!-- Compare Panel -->
      <template v-if="activeTab === 'compare'">
        <div class="bg-[var(--canvas)] rounded-lg p-3 border border-[var(--border)] flex-1 min-w-[340px]">
          <div class="font-semibold text-[var(--ink-muted-48)] uppercase tracking-widest mb-2 text-[11px]">
            Compare Heads — Layer {{ selectedLayer }}
          </div>
          <div class="flex gap-2 mb-2">
            <select v-model.number="compareHeads[0]"
              class="bg-[var(--canvas-parchment)] text-[var(--ink)] border border-[var(--border)] rounded px-1 py-0.5 text-[11px]">
              <option v-for="(l, i) in headLabels" :key="i" :value="i">{{ l }}</option>
            </select>
            <span class="text-[var(--ink-muted-48)] self-center">vs</span>
            <select v-model.number="compareHeads[1]"
              class="bg-[var(--canvas-parchment)] text-[var(--ink)] border border-[var(--border)] rounded px-1 py-0.5 text-[11px]">
              <option v-for="(l, i) in headLabels" :key="i" :value="i">{{ l }}</option>
            </select>
          </div>
          <template v-if="layer?.heads[compareHeads[0]]?.attentionMatrix && layer?.heads[compareHeads[1]]?.attentionMatrix">
            <div class="flex gap-2">
              <div class="flex-1">
                <div class="text-[10px] text-[var(--ink-muted-48)] mb-1">Head {{ compareHeads[0] }}</div>
                <AttentionHeatmap :matrix="layer.heads[compareHeads[0]].attentionMatrix"
                  :tokens="tokens" :hoveredToken="null" @hoverToken="() => {}" />
              </div>
              <div class="flex-1">
                <div class="text-[10px] text-[var(--ink-muted-48)] mb-1">Head {{ compareHeads[1] }}</div>
                <AttentionHeatmap :matrix="layer.heads[compareHeads[1]].attentionMatrix"
                  :tokens="tokens" :hoveredToken="null" @hoverToken="() => {}" />
              </div>
            </div>
          </template>
          <div v-else class="text-[var(--ink-muted-48)] text-xs">Run a prompt first.</div>
        </div>

        <div class="bg-[var(--canvas)] rounded-lg p-3 border border-[var(--border)] flex-1 min-w-[340px]">
          <div class="font-semibold text-[var(--ink-muted-48)] uppercase tracking-widest mb-2 text-[11px]">
            Head Similarity — Layer {{ selectedLayer }}
          </div>
          <div class="flex flex-wrap gap-1">
            <div v-for="(s, i) in layerHeadSummaries" :key="i"
              class="w-9 h-9 rounded flex items-center justify-center text-[9px] font-semibold cursor-pointer border border-[var(--border)]"
              :style="{ background: rgbaPrimary(0.1 + (s.avgActivation / maxAvgActivation) * 0.9),
                         color: (s.avgActivation / maxAvgActivation) > 0.5 ? 'var(--on-dark)' : 'var(--ink)' }"
              @click="selectedHead = i; activeTab = 'attention'"
              :title="`H${i}: avg=${s.avgActivation.toFixed(3)}, max=${s.maxActivation.toFixed(3)}`">
              H{{ i }}
            </div>
          </div>
        </div>
      </template>
    </div>

    <!-- ── Neuron UMAP ─────────────────── -->
    <div v-if="activeTab === 'umap'" class="bg-[var(--canvas)] rounded-lg p-3 border border-[var(--border)] w-full">
      <div class="font-semibold text-[var(--ink-muted-48)] uppercase tracking-widest mb-2 text-[11px]">
        Neuron Map — All Layers &amp; Heads
      </div>
      <NeuronUMAPWrapper :points="umapPoints" :tokens="tokens"
        :selectedId="selectedNeuron != null ? idForHeadNeuron(selectedLayer, selectedHead, selectedNeuron) : null"
        @selectNeuron="handleUmapSelect" :height="460" />
    </div>

    <!-- ── Token Detail ─────────────────── -->
    <div v-if="hoveredToken != null && tokens[hoveredToken] && neurons.length > 0"
      class="bg-[var(--canvas)] rounded-lg p-3 border border-[var(--border)]">
      <div class="font-semibold text-[var(--ink-muted-48)] uppercase tracking-widest mb-2 text-[11px]">
        Neurons Active for "{{ tokens[hoveredToken] }}" (token {{ hoveredToken }})
      </div>
      <ActivationHeatmap :activations="neurons.map(n => n.activation)"
        :neuronIndex="selectedNeuron"
        @selectNeuron="(i) => selectedNeuron = i"
        :tokens="tokens"
        :neuronTokenActivations="neurons.map(n => n.tokenActivations ?? null)" />
    </div>

    <!-- ── Summary Bar ──────────────────── -->
    <div class="flex gap-2 flex-wrap text-[11px] text-[var(--ink-muted-48)]">
      <span>Layers: {{ numLayers }}</span>
      <span>Heads/Layer: {{ numHeads }}</span>
      <span>Neurons/Layer: {{ neurons.length }}</span>
      <span>Tokens: {{ tokens.length }}</span>
      <template v-if="selNeuronData">
        <span>Neuron #{{ selNeuronData.index }} activation: {{ selNeuronData.activation.toFixed(4) }}</span>
      </template>
      <template v-if="hoveredToken != null && tokens[hoveredToken]">
        <span>Token: "{{ tokens[hoveredToken] }}"</span>
      </template>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, computed } from 'vue';
import { colors } from '../../design/tokens/colors';
import { AttentionHeatmap } from './panels/AttentionHeatmap';
import { ActivationHeatmap } from './panels/ActivationHeatmap';
import NeuronUMAPWrapper from './neuron-umap/NeuronUMAPWrapper.vue';
import { buildNeuronPoints, idForHeadNeuron, parseNeuronId } from './neuron-umap/data';

/* ── props ──────────────────────────────────────── */
const props = withDefaults(defineProps<{
  tokens: string[];
  layers: any[];
  numLayers: number;
  numHeads: number;
}>(), {
  tokens: () => [],
  layers: () => [],
  numLayers: 0,
  numHeads: 0,
});

/* ── state ──────────────────────────────────────── */
const selectedLayer = ref(0);
const selectedHead = ref(0);
const selectedNeuron = ref<number | null>(null);
const hoveredToken = ref<number | null>(null);
const activeTab = ref<'attention' | 'neurons' | 'spectrum' | 'compare' | 'umap'>('attention');
const compareHeads = ref<number[]>([0, 1]);

const tabs = ['attention', 'neurons', 'spectrum', 'compare', 'umap'] as const;

/* ── computed ───────────────────────────────────── */
const layer = computed(() => props.layers?.[selectedLayer.value]);
const head = computed(() => layer.value?.heads[selectedHead.value]);
const neurons = computed(() => head.value?.neurons ?? []);
const matrix = computed(() => head.value?.attentionMatrix ?? []);

const headLabels = computed(() => Array.from({ length: props.numHeads }, (_, i) => `H${i}`));

const selNeuronData = computed(() => {
  if (selectedNeuron.value == null) return null;
  return neurons.value[selectedNeuron.value] ?? null;
});

const umapPoints = computed(() => buildNeuronPoints(props.layers, props.tokens));

const layerHeadSummaries = computed(() => {
  if (!layer.value) return [];
  return layer.value.heads.map((h: any, i: number) => {
    const flat = (h.attentionMatrix as number[] | undefined)?.flat() ?? [];
    return {
      headIndex: i,
      avgActivation: flat.reduce((a: number, b: number) => a + b, 0) / (flat.length || 1),
      maxActivation: Math.max(...(flat.length ? flat : [0])),
    };
  });
});

const maxAvgActivation = computed(() => {
  const vals = layerHeadSummaries.value.map((x: any) => x.avgActivation);
  return Math.max(...vals, 0.01);
});

/* ── helpers ────────────────────────────────────── */
function hexToRgb(hex: string): [number, number, number] {
  const n = parseInt(hex.slice(1), 16);
  return [(n >> 16) & 255, (n >> 8) & 255, n & 255];
}

function rgbaPrimary(a: number): string {
  const [r, g, b] = hexToRgb(colors.primary);
  return `rgba(${r},${g},${b},${a})`;
}

function handleUmapSelect(id: string) {
  const parsed = parseNeuronId(id);
  if (!parsed) { selectedNeuron.value = null; return; }
  if (parsed.head !== undefined) {
    selectedLayer.value = parsed.layer;
    selectedHead.value = parsed.head;
  }
  selectedNeuron.value = parsed.neuron;
}
</script>
